### ISSUE TITLE
自定义组件类型声明文件出现冲突

### ISSUE THREAD

**Issue by Megasu** [uni-helper/uni-app-types#16]
### 描述问题

自定义组件的类型声明文件 `components.d.ts` 与 `@uni-helper/uni-app-types` 类型出现冲突。

## 复现步骤

1. 新建自定义类型声明文件 `src\components\components.d.ts`，并添加全局组件类型声明：
```ts
declare module 'vue' {
  export interface GlobalComponents {
    // 组件路径已确认无误
    XtxCarousel: typeof import('./XtxCarousel.vue')['default']
  }
}
export {}
```
2. 最终导致 `@uni-helper/uni-app-types` 所提供的组件类型失效了，所有 uni-app 组件鼠标悬停类型为 unknow。
3. 目前自己通过三斜杠引用方式解决冲突，自定义全局组件类型和  `@uni-helper/uni-app-types` 可以共存。
```ts
// 通过三斜杠引用
/// <reference types="@uni-helper/uni-app-types" />

declare module 'vue' {
  export interface GlobalComponents {
    XtxCarousel: typeof import('./XtxCarousel.vue')['default']
  }
}
export {}
```

### 其他补充
tsconfig.json 的 types 其实可以删除掉
```diff
{
  "compilerOptions": {
    "types": [
      "@dcloudio/types",
-      "@uni-helper/uni-app-types"
    ]
  },
  "vueCompilerOptions": {
    "nativeTags": ["block", "component", "template", "slot"]
  },
}

```

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 3.38 GB / 15.79 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (108.0.1462.54)
    Internet Explorer: 11.0.22000.120

VsCode 1.74.1
Volar  v1.0.16

"@uni-helper/uni-app-types": "0.3.0",
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Megasu** [comment]
全局组件在 `src\pages.json` 中通过 `easycom` 配置自动注册，在项目中全局组件可正常工作。

```jsonc
{
  "easycom": {
    "autoscan": true,
    "custom": {
      // 自定义全局组件，把 components 文件夹中以 Xtx 开头的 vue 组件，注册为全局组件
      "^Xtx(.*)": "@/components/Xtx$1.vue"
    }
  },
}
```

**Comment by ModyQyW** [comment]
我这里复现不出来。方便的话可以给个 demo？

两个点我比较在意。

1. uni-app-types 里面全局组件的定义都是基于 `@vue/runtime-core` 的，而你给出的示例是 `declare module 'vue'`，不太确定有没有影响。

<img width="687" alt="image" src="https://user-images.githubusercontent.com/31850793/209067380-2948d318-44f8-4ee2-afb2-32881716b15d.png">

2. tsconfig.json 有没有 include 这个 components.d.ts？

**Comment by Megasu** [comment]
demo地址：https://gitee.com/Megasu/uni-app-types-demo

1. 自定义的类型声明文件需要写成  `declare module 'vue'` 写成 `@vue/runtime-core` 反而无法工作。
2. tsconfig.json 有没有 include 这个 components.d.ts？有的，默认模板中自动加载 src 目录下所有的  d.ts 文件。
```json
"include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
```

**Comment by Megasu** [comment]
> demo地址：https://gitee.com/Megasu/uni-app-types-demo
> 
> 1. 自定义的类型声明文件需要写成  `declare module 'vue'` 写成 `@vue/runtime-core` 反而无法工作。
> 2. tsconfig.json 有没有 include 这个 components.d.ts？有的，默认模板中自动加载 src 目录下所有的  d.ts 文件。
> 
> ```json
> "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"]
> ```

请问作者您那边能复现问题吗？ @ModyQyW

**Comment by ModyQyW** [comment]
我这边使用了你提供的 demo。components.d.ts 里面写成 `declare module 'vue'` 和 `declare module '@vue/runtime-core'` 都能正常工作，而且不需要三斜线指令。

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/209083084-b3ede604-62dd-41de-8734-f6017d30140e.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/209083123-8dbb99b8-952c-46a5-855e-f7042364c70d.png">

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/209083188-bbafa1d5-4708-489b-9736-49dd6883b69b.png">

**Comment by ModyQyW** [comment]
[volar 官方文档](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features)建议 vue 3 使用 `declare module '@vue/runtime-core'`。

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/31850793/209084117-5d06faa2-c1fc-47a5-963c-28b535b09be7.png">

**Comment by ModyQyW** [comment]
我觉得需要你检查一下 VSCode 本地配置，包括 [Volar](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features) 和 [Take Over Mode](https://cn.vuejs.org/guide/typescript/overview.html#volar-takeover-mode)，最后需要 Reload Window 试一下。看起来我这边无能为力。

**Comment by Megasu** [comment]
> [volar 官方文档](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features)建议 vue 3 使用 declare module '@vue/runtime-core'。

1. 按官方建议修改后反而类型失效
2. 已清空所有 VsCode 本地配置
3. 已开启 [Volar](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features) 和 [Take Over Mode](https://cn.vuejs.org/guide/typescript/overview.html#volar-takeover-mode)
4. 已 Reload Window 设置是重启编辑器。

![image](https://user-images.githubusercontent.com/7400870/209087475-7da37924-8da7-4bde-b272-1ff7b9f31a75.png)

**Comment by Megasu** [comment]
Vant 组件库也是通过 declare module 'vue' 注册类型的
```ts
declare module 'vue' {
  export interface GlobalComponents {
    VanButton: typeof Button;
  }
}
```

源码地址：https://github.com/youzan/vant/blob/main/packages/vant/src/button/index.ts

**Comment by Megasu** [comment]
我也无法定位到 Bug 的原因，目前我和我同事都只能通过 `declare module 'vue'` 注册全局组件的类型，用 `declare module '@vue/runtime-core'` 反而不行。

![image](https://user-images.githubusercontent.com/7400870/209088665-5799f42a-a0c4-4d62-a593-18c2e84fdfaa.png)

**Comment by Megasu** [comment]
> [volar 官方文档](https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features)建议 vue 3 使用 `declare module '@vue/runtime-core'`。
> 
> <img alt="image" width="1058" src="https://user-images.githubusercontent.com/31850793/209084117-5d06faa2-c1fc-47a5-963c-28b535b09be7.png">

其实我也不知道 Volar 作者为什么定义全局组件的类型还要分 Vue 的版本写，为什么不能统一写法，同时按官方要求用 `declare module '@vue/runtime-core'` 反而无法工作。

**Comment by Megasu** [comment]
我是觉得非常奇怪，为什么同样的代码，您那边可以正常运行，为了排除变化，我已经注释掉了所有设置，还是一样情况。

> 我这边使用了你提供的 demo。components.d.ts 里面写成 `declare module 'vue'` 和 `declare module '@vue/runtime-core'` 都能正常工作，而且不需要三斜线指令。
> 
> <img alt="image" width="1920" src="https://user-images.githubusercontent.com/31850793/209083084-b3ede604-62dd-41de-8734-f6017d30140e.png">
> 
> <img alt="image" width="1920" src="https://user-images.githubusercontent.com/31850793/209083123-8dbb99b8-952c-46a5-855e-f7042364c70d.png">
> 
> <img alt="image" width="1920" src="https://user-images.githubusercontent.com/31850793/209083188-bbafa1d5-4708-489b-9736-49dd6883b69b.png">

**Comment by ModyQyW** [comment]
我也正在迷惑这一点……

**Comment by Megasu** [comment]
刚刚通过 `pnpm i -D @vue/runtime-core` ，需要显性的安装了 `@vue/runtime-core` 才行。
显式安装后依赖包后就不出现冲突了，可以删除掉三斜杠的引入。
问题虽然解决了，但是还是存在一些迷惑。🥲

**Comment by ModyQyW** [comment]
这真的挺诡异的。因为 vue 本身 dependencies 里有 @vue/runtime-core，不明白为什么没有安装上。

**Comment by ModyQyW** [comment]
但解决了就好。

**Comment by Zhang-Wei-666** [comment]
@Megasu

你用的 pnpm, 这是由于 pnpm 默认的文件结构导致的
要在项目根目录创建 `.npmrc` 文件, 并添加 `shamefully-hoist=true`
之后重新运行 `pnpm install`, 重启编辑器, 就没问题了

这是配置前
![image](https://user-images.githubusercontent.com/37876877/212832808-7490d9fe-a6ad-4769-ba6a-3ecf35a1e29f.png)

这是配置后
![image](https://user-images.githubusercontent.com/37876877/212832703-ea1d9cce-67fd-4dfd-9faa-8937dff9e7eb.png)

**Comment by ModyQyW** [comment]
确实是。我之前设了全局的 `.npmrc` 都忘了🤦

**Comment by Megasu** [comment]
@Zhang-Wei-666 非常感谢。❤️
