### ISSUE TITLE
降低类型使用成本

### ISSUE THREAD

**Issue by Megasu** [uni-helper/uni-app-types#3]
### 描述问题

![image](https://user-images.githubusercontent.com/7400870/205206288-d54b2c7e-05d5-4508-9c1b-d35cf37bd839.png)

### 复现

```vue
<script setup lang="ts">
import { ref } from 'vue'

const source = ref([
  {
    id: 1,
    imgUrl:
      'https://pcapi-xiaotuxian-front-devtest.itheima.net/miniapp/uploads/slider_1.jpg',
  },
  {
    id: 2,
    imgUrl:
      'https://pcapi-xiaotuxian-front-devtest.itheima.net/miniapp/uploads/slider_2.jpg',
  },
  {
    id: 3,
    imgUrl:
      'https://pcapi-xiaotuxian-front-devtest.itheima.net/miniapp/uploads/slider_3.jpg',
  },
])

const activeIndex = ref(0)
// BUG: change 类型错误，不能使用 WechatMiniprogram.SwiperChange
const onSwiperChange = (ev: WechatMiniprogram.SwiperChange) => {
  activeIndex.value = ev.detail.current
}
</script>

<template>
  <view class="carousel">
    <swiper circular autoplay :interval="3000" @change="onSwiperChange">
      <swiper-item v-for="item in source" :key="item.id">
        <navigator
          url="/pages/index/index"
          hover-class="none"
          class="navigator"
        >
          <image mode="aspectFill" class="image" :src="item.imgUrl"></image>
        </navigator>
      </swiper-item>
    </swiper>
    <view class="indicator">
      <text
        v-for="(item, index) in source"
        :key="item.id"
        class="dot"
        :class="{ active: index === activeIndex }"
      ></text>
    </view>
  </view>
</template>

<style lang="scss">
:host {
  display: block;
  height: 280rpx;
}
/* 焦点图 */
.carousel {
  height: 100%;
  position: relative;
  overflow: hidden;
  transform: translateY(0);
  background-color: #efefef;
  .indicator {
    position: absolute;
    left: 0;
    right: 0;
    bottom: 16rpx;
    display: flex;
    justify-content: center;
    .dot {
      width: 30rpx;
      height: 6rpx;
      margin: 0 8rpx;
      border-radius: 6rpx;
      background-color: rgba(255, 255, 255, 0.4);
    }
    .active {
      background-color: #fff;
    }
  }
  .navigator,
  .image {
    width: 100%;
    height: 100%;
  }
}
</style>

```

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 4.08 GB / 15.79 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.22000.120
VSCode   1.73.1
Volar    1.0.10
vue-tsc  1.0.10
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
按我的理解，你这里提出的是两个问题的结合。

第一个问题：怎么为回调事件标注类型？实际上，`@uni-helper/uni-app-types` 导出了相关的类型，你可以导入后使用。

```vue
<script setup lang="ts">
import type { SwiperProps } from '@uni-helper/uni-app-types';

const onSwiperChange: SwiperProps['onChange'] = (event) => {
  activeIndex.value = event.detail?.current;
};
</script>

```

第二个问题：能不能支持小程序平台原生类型？这有待商榷。原因如下：

1. `uni-app` 修改了底层事件处理以适配不同的小程序平台，所以事件回调参数不能使用小程序平台的原生类型。官方没有明确说明这一点，我在实际开发中发现确实会有这种情况发生。
2. 目前我知道的，只有微信小程序和支付宝小程序提供了事件类型，没法覆盖全部小程序平台。

如果我误会了你的意思，请指出，我们友好讨论，谢谢。@Megasu

**Comment by Megasu** [comment]
@ModyQyW Hi，作者你好

其实我的问题应该是：能不能支持小程序平台原生类型？(问题二)

## 关于问什么
1. 小程序平台主要是微信小程序平台为主。
2. 只有微信小程序和支付宝小程序提供了事件类型。

## 期待
支持小程序平台原生类型的写法：
```vue
<script setup lang="ts">
const onSwiperChange = (ev: WechatMiniprogram.SwiperChange) => {
  activeIndex.value = ev.detail.current
}
</script>
```

目前 `@uni-helper/uni-app-types` 导出的类型使用成本有点高：
```vue
<script setup lang="ts">
import type { SwiperProps } from '@uni-helper/uni-app-types';

const onSwiperChange: SwiperProps['onChange'] = (event) => {
  activeIndex.value = event.detail?.current ?? activeIndex.value;
};
</script>
```

## 讨论
关于作者提及的这两点：
> 1. uni-app 修改了底层事件处理以适配不同的小程序平台，所以事件回调参数不能使用小程序平台的原生类型。官方没有明确说明这一点，我在实际开发中发现确实会有这种情况发生。
> 2. 目前我知道的，只有微信小程序和支付宝小程序提供了事件类型，没法覆盖全部小程序平台。

这两天我也有在思考，大致想到的方案如下：
1. 是否可以把类型分为两部分，一部分是组件属性的类型，一部分是组件的事件类型，开发者自行选择。
2. 不提供组件的事件类型，由开发者根据自己要兼容的平台自行指定。(因为没法覆盖全部小程序平台)
3. 考虑支持以下写法，兼容已知的**微信小程序和支付宝小程序提供的事件类型**：
```vue
<script setup lang="ts">
const onSwiperChange = (ev: UniHelper.SwiperChange) => {
  activeIndex.value = ev.detail.current
}
</script>
```

## 平衡
我提建议的依据主要是由两点：
1. 作者维护成本问题，作者维护成功不能过高，毕竟平台会持续更新，最好能自动化完成。
2. 开发者使用成本问题，开发者书写不能太高，否则开发的实际体验会大打折扣。

## 感谢
🌹 感谢作者的开源贡献。

**Comment by ModyQyW** [comment]
> 这两天我也有在思考，大致想到的方案如下：
>
> 1. 是否可以把类型分为两部分，一部分是组件属性的类型，一部分是组件的事件类型，开发者自行选择。
> 2. 不提供组件的事件类型，由开发者根据自己要兼容的平台自行指定。(因为没法覆盖全部小程序平台)
> 3. 考虑支持以下写法，兼容已知的微信小程序和支付宝小程序提供的事件类型

1 是可以的，但是需要考虑下拆分后命名的问题，避免出现误导。
2 不提供会降低开发者体验，既然叫做 uni-app-types，应该要提供 uni-app 文档上有的类型才对。
3 很合理，也能降低类型使用成本，就是 namespace 需要确认一下。

综上所述，我觉得可以在 0.3.0 加入你第一点和第三点建议，第二点建议会降低开发者体验，不做考虑。这可能会是一个 breaking change，而且uni-cloud-types 和 uni-ui-types 也会跟随以上改动，所以我必须仔细斟酌一下，请见谅。如果你有兴趣，也欢迎 PR。

**Comment by Megasu** [comment]
🌹，期待中。

**Comment by ModyQyW** [comment]
应该会重点参考 @dcloudio/types 和 element-plus 的类型。

可能会在1-2个月内完成。

**Comment by Megasu** [comment]
> 如果你有兴趣，也欢迎 PR。

作者您设计好 0.3.0 的架子和 PR 要求，我和我的团队可以立刻跟进。🌹

**Comment by ModyQyW** [comment]
@uni-helper/uni-app-types@0.3.0-3 已经发布，如无意外应该会是 0.3.0 前最后一个测试版本。后续 uni-ui-types 和 uni-cloud-types 会跟进。

**Comment by ModyQyW** [comment]
@uni-helper/uni-ui-types 和 @uni-helper/uni-cloud-types 已经跟进完毕了。如果没有什么问题，周三或者周四就会发三个包的 0.3.0。

这个 issue 就先关掉了，有问题可以另开 issue，谢谢。

**Comment by ModyQyW** [comment]
已经发布 0.3.0 了。有问题可以提 issue 或者 PR 的。谢谢。

**Comment by Megasu** [comment]
感谢~

**Comment by Megasu** [comment]
之前提出兼容小程序端类型的想法有局限性，需求应该是 `UniHelper` 提供 `event` 事件类型。

```vue
<script setup lang="ts">
const onSwiperChange = (ev: UniHelper.SwiperOnChangeEvent) => {
  activeIndex.value = ev.detail.current
}
</script>
```
