### ISSUE TITLE
@vue/server-renderer依赖版本跟uni官方提供的vue库依赖版本不一致

### ISSUE THREAD

**Issue by IvoHu** [uni-helper/uni-app-types#30]
### 描述问题

├─┬ @uni-helper/uni-app-types@0.4.0
│ └─┬ vue3@npm:vue@3.2.47
│   └─┬ @vue/server-renderer@3.2.47
│     └── vue@3.2.45 deduped invalid: "3.2.47" from node_modules/vue3/node_modules/@vue/server-renderer

npm list vue报错，项目其他uni库依赖3.2.45

### 复现

npm list vue报错

├─┬ @uni-helper/uni-app-types@0.4.0
│ └─┬ vue3@npm:vue@3.2.47
│   └─┬ @vue/server-renderer@3.2.47
│     └── vue@3.2.45 deduped invalid: "3.2.47" from node_modules/vue3/node_modules/@vue/server-renderer

### 系统信息

```Shell
System:
    OS: macOS 12.6.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Memory: 155.03 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - ~/node_modules/.bin/node
    Yarn: 3.4.1 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Safari: 15.6.1
```

### 使用的包管理器

npm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
请问能正常跑起来吗？

**Comment by ModyQyW** [comment]
我刚刚用 `npx degit dcloudio/uni-preset-vue#vite-ts playground` 克隆了一个新项目。

如果使用 npm 8 没有设置 `legacy-peer-deps` 为 true，根本无法安装依赖。

```shell
➜  [/Users/wurui/Documents/playground] npm i       
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: uni-preset-vue@0.0.0
npm ERR! Found: vite@4.0.4
npm ERR! node_modules/vite
npm ERR!   dev vite@"4.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vite@"4.0.3" from @dcloudio/vite-plugin-uni@3.0.0-alpha-3061620221230002
npm ERR! node_modules/@dcloudio/vite-plugin-uni
npm ERR!   dev @dcloudio/vite-plugin-uni@"3.0.0-alpha-3061620221230002" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/wurui/.npm/_logs/2023-02-09T13_31_05_187Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wurui/.npm/_logs/2023-02-09T13_31_05_187Z-debug-0.log
```

模板使用的是 vite@4.0.4，@dcloudio/vite-plugin-uni 使用的却是 vite@4.0.3，导致依赖装不上。这属于是 uni-app 官方没处理好版本的问题。

目前建议是使用 `npm i --legacy-peer-deps` 或者在 `.npmrc` 里设置 `legacy-peer-deps=true` 来规避这个问题。后续会在 README 中更新相关的说明。

如果在运行过程中有实际报错而导致项目项目无法运行，请提供最小复现，否则可无视。

**Comment by IvoHu** [comment]
能跑起来，目前错误基本都能解决

**Comment by ModyQyW** [comment]
能正常跑起来就可以。如果还是很在意依赖版本问题可以到 uni-app 仓库提 issue。

**Comment by IvoHu** [comment]
恩好的。谢谢啦
