### ISSUE TITLE
建议增加组件 event 类型

### ISSUE THREAD

**Issue by Megasu** [uni-helper/uni-app-types#31]
### 使用疑惑

传递多个参数的时候，如何校验参数的类型。

![image](https://user-images.githubusercontent.com/7400870/221807861-b55f94a4-9711-41e5-9179-4d5bb73abec5.png)

```tsx
// swiper 组件
<swiper @change="onChange($event, 1)"></swiper>

// 当 swiper 下标发生变化时
const onChange: UniHelper.SwiperOnChange = (ev, param: number) => {
  // ...省略
}
```

### 预期效果

提供组件的 event 类型，添加到 UniHelper 命名空间上。

![image](https://user-images.githubusercontent.com/7400870/221815894-3fea949e-5b96-4931-b009-51281bd005cc.png)

### 参考代码
```diff
declare global {
  namespace UniHelper {
    export interface SwiperOnChangeDetail extends _SwiperOnChangeDetail {}
+   // 增加导出 event 类型
+   export interface SwiperOnChangeEvent extends CustomEvent<_SwiperOnChangeDetail> {}
    ...省略
  }
}
```

### 替代方案

也可通过 `Parameters` 提取 event 类型，但写法使用成本较高。

![image](https://user-images.githubusercontent.com/7400870/221811836-f2111937-00ae-471e-ae21-271430110c6f.png)

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
好提议。我觉得可以拆分成两个 PR。

一个 PR 补充所有组件的 event 类型，如 `SwiperOnChangeEvent` 等。

另一个 PR 调整事件的实现，下面是一个例子。

```typescript
interface _SwiperOnChange {
  // PR 前
  (event: CustomEvent<_SwiperOnChangeDetail>): void;
  // PR 后
  (event: CustomEvent<_SwiperOnChangeDetail>, ...params: any[]): void;
}
```

最近公司业务比较紧，我可能会稍晚一点提交这两个 PR 😅。当然也欢迎提交 PR 做相关实现！

**Comment by Megasu** [comment]
👌 已提交 PR 调整事件的实现。

**Comment by Megasu** [comment]
关于事件的类型还有个问题想讨论一下。

### 疑惑

疑惑：自定义事件类型 `CustomEvent` 是出于什么考虑把 `detail` 属性调整成可选属性。

### 代码对比
原生微信小程序的 [CustomEvent类型声明](https://github.com/wechat-miniprogram/api-typings/blob/master/types/wx/lib.wx.event.d.ts#L55-L64)：
```ts
/*! *****************************************************************************
Copyright (c) 2023 Tencent, Inc. All rights reserved.
***************************************************************************** */
/** 自定义事件 */
interface CustomEvent<
    Detail extends IAnyObject = IAnyObject,
    Mark extends IAnyObject = IAnyObject,
    CurrentTargetDataset extends IAnyObject = IAnyObject,
    TargetDataset extends IAnyObject = CurrentTargetDataset
> extends BaseEvent<Mark, CurrentTargetDataset, TargetDataset> {
    /** 额外的信息 */
    detail: Detail
}
```
`UniHelper` 的 [CustomEvent类型声明](https://github.com/uni-helper/uni-app-types/blob/main/types/events/index.d.ts#L38-L48)：
```ts
/** 自定义事件 */
interface _CustomEvent<
  Detail extends AnyRecord = AnyRecord,
  Mark extends AnyRecord = AnyRecord,
  CurrentTargetDataset extends AnyRecord = AnyRecord,
  TargetDataset extends AnyRecord = CurrentTargetDataset,
> extends _BaseEvent<Mark, CurrentTargetDataset, TargetDataset> {
  /** 额外信息，变成可选属性，目前不清楚您的出发点，可以交流一下🤔 */
  detail?: Detail;
  [key: string]: any;
}
```

### 带来的影响
![image](https://user-images.githubusercontent.com/7400870/222122418-2bfc8884-2f04-48cc-9446-31e4f420ad0f.png)


### 预期效果
![image](https://user-images.githubusercontent.com/7400870/222122605-4793777a-a70e-46be-b220-b01b4d697923.png)

**Comment by ModyQyW** [comment]
已经增加 `XxxEvent` 类型啦！非常感谢🙏
