### ISSUE TITLE
Volar 更新到 1.0.10 后配置失效

### ISSUE THREAD

**Issue by Megasu** [uni-helper/uni-app-types#4]
### 1.0.10 (2022/11/29)

feat: add nativeTags instead of experimentalRuntimeMode to vueCompilerOptions for uni-app supports (https://github.com/johnsoncodehk/volar/issues/2065)

### 解决方案
```diff
{
  "compilerOptions": {
    "types": ["@dcloudio/types", "@uni-helper/uni-app-types"]
  },
  "vueCompilerOptions": {
-    "experimentalRuntimeMode": "runtime-uni-app"
+    "nativeTags": []
  },
  "include": ["src/**/*.vue"]
}
```

## 复现方案
把 Volar 更新到最新的 v1.0.10 便会出现

### 1.0.10 (2022/11/29)

feat: add **nativeTags** instead of **experimentalRuntimeMode** to vueCompilerOptions for uni-app supports (https://github.com/johnsoncodehk/volar/issues/2065)

### 解决方案
```diff
{
  "compilerOptions": {
    "types": ["@dcloudio/types", "@uni-helper/uni-app-types"]
  },
  "vueCompilerOptions": {
-    "experimentalRuntimeMode": "runtime-uni-app"
+    "nativeTags": []
  },
  "include": ["src/**/*.vue"]
}
```

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i7-1195G7 @ 2.90GHz
    Memory: 4.08 GB / 15.79 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 9.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (107.0.1418.56)
    Internet Explorer: 11.0.22000.120
Volar    1.0.10
vue-tsc  1.0.10
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
感谢你的指出！

直接移除 `"experimentalRuntimeMode": "runtime-uni-app"` 可能会导致锁定 `Volar` 和 `vue-tsc` 到 1.0.9 的项目类型提示错误。我会尽快更新文档并添加指引。

**Comment by ModyQyW** [comment]
先等待 <https://github.com/johnsoncodehk/volar/issues/2165> 的回复

**Comment by ModyQyW** [comment]
https://github.com/johnsoncodehk/volar/issues/2165#issuecomment-1334803492

晚一点发一个 v0.2.0

**Comment by ModyQyW** [comment]
v0.2.0 已经发布，请阅读 README 并调整。再次感谢你指出了这个问题。❤

**Comment by Megasu** [comment]
作者更新很及时，再次感谢。❤
