### ISSUE TITLE
volar / vue-tsc@^1.6.4 该如何配置？

### ISSUE THREAD

**Issue by zhuddan** [uni-helper/uni-app-types#44]
### 描述问题

你好！我有一个项目已经配合[vue3.3](https://blog.vuejs.org/posts/vue-3-3)发布进行了升级 volar 和 vue-tsc 但是不能正常工作

出现了类似这个[issue](https://github.com/uni-helper/uni-app-types/issues/43) 的问题

### 复现

项目根目录 tsconfig.json
``` json
{
  "extends": "@vue/tsconfig/tsconfig.json",
  "compilerOptions": {
    "sourceMap": true,
    "lib": ["esnext", "dom"],
    "resolveJsonModule": true,
    "types": [
      "@dcloudio/types",
      "@uni-helper/uni-app-types",
      "@uni-helper/uni-ui-types"
    ]
  }
}
```

项目 json 配置
``` json
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue",
    "auto-imports.d.ts",
    "vite.config.ts"
  ]
}

```

使用时报错 
```vue
<button type="primary"  > // Type '"primary"' is not assignable to type '"button" | "submit" | "reset" |  undefined
      新增
</button>
```
button 类型
![image](https://github.com/uni-helper/uni-app-types/assets/32126992/9f9f227b-95fc-4674-a5aa-c3f65ac2aced)

请问我该怎么办

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 12th Gen Intel(R) Core(TM) i7-1260P
    Memory: 1.99 GB / 15.73 GB
  Binaries:
    Node: 16.19.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 8.19.3 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22621.1555.0), Chromium (113.0.1774.35), ChromiumDev (115.0.1843.0)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by zhuddan** [comment]
ps @uni-helper/uni-app-types 版本为 ^0.5.7 "@dcloudio/types为^3.3.3

**Comment by zhuddan** [comment]
泛型组件 和 slots 类型 太香了 ，不是很想退。。。

等你有时间再改好把
我先将就用着，打包之类的也不影响，就是ide报个错
麻烦了

**Comment by ModyQyW** [comment]
试着覆盖 @vue/runtime-dom 的类型但没有效果……

@KeJunMao @zguolee @hairyf 大哥们有无头绪？教教 😭

**Comment by KeJunMao** [comment]
这样不行吗？
```ts
declare module '@vue/runtime-dom' {
  export interface ButtonHTMLAttributes extends _Button {}

  export interface IntrinsicElementAttributes {
    /** 按钮 */
    button: ButtonHTMLAttributes;
  }
}

```

**Comment by ModyQyW** [comment]
> 这样不行吗？ vue3.3.2，volar1.7.3
> 
> ```ts
> declare module '@vue/runtime-dom' {
>   export interface ButtonHTMLAttributes extends _Button {}
> 
>   export interface IntrinsicElementAttributes {
>     /** 按钮 */
>     button: ButtonHTMLAttributes;
>   }
> }
> ```
> 
> ![image](https://user-images.githubusercontent.com/18414281/238307400-0793ff03-5006-4a6b-829f-94c5bcaff55d.png)

不太行，这种做法的话 view 和 text 没法同时处理，都是用的 SVGAttributes 

![e42ae091d4097c1725d3f0b76941831c](https://github.com/uni-helper/uni-app-types/assets/31850793/6ff0757b-2b1a-4926-800b-9721b4189da3)

![f5f8731933dcd6b9f6e3bebc008321d1](https://github.com/uni-helper/uni-app-types/assets/31850793/4b7dd33f-64dd-4c9f-ac5a-135e3328e0ee)

**Comment by ModyQyW** [comment]
刚刚发布了 0.5.8-0，明天会做更详尽的测试（vue2.6.14，vue3.2.47，vue3.3）

**Comment by ModyQyW** [comment]
0.5.8 已经发布！如果有问题请反馈，谢谢 🙏 @zhuddan

**Comment by WuMrZore** [comment]
<img width="1435" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/76389859/dbbabf4f-ac7a-4815-a59a-32953c4fbd9a">
<img width="249" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/76389859/67101719-3cd6-4e4f-94ae-fe68f402cd15">

我这没有正常工作，很奇怪
vue：3.2.47
valar: 1.7.6

**Comment by zhuddan** [comment]
@WuMrZore 请升级vue到3.3

**Comment by WuMrZore** [comment]
> @WuMrZore 请升级vue到3.3

我的项目是 uniapp，现在 uniapp 还不支持 vue3.3 吧？

**Comment by zhuddan** [comment]
@WuMrZore 我升级了是没有问题的，至少现在开发或者打包还没有遇到问题。。。如果你坚持要用3.2，请把@uni-helper/uni-app-types 版本降低为0.5.7。如果想升级3.3的话参考[这个](https://blog.vuejs.org/posts/vue-3-3)

**Comment by ModyQyW** [comment]
@WuMrZore  volar 1.6.5 正常吗？

**Comment by ModyQyW** [comment]
@WuMrZore  我自己这边复现不出来，如果方便的话麻烦再开个pr提供下完整的信息🙏

**Comment by WuMrZore** [comment]
> @WuMrZore 我自己这边复现不出来，如果方便的话麻烦再开个 issue 提供下完整的信息🙏

我也不知道为啥，我先再观察观察
