### ISSUE TITLE
`nativeTags` Usage problem

### ISSUE THREAD

**Issue by Ares-Chang** [uni-helper/uni-app-types#46]
您好，我在引用这个包的时候发现一个问题，

我如果只在 `tsconfig` 中配置 `compilerOptions.types` 引入的话，只有部分组件能正常引导类型。

但是如下图中，`image` 组件并不能带出我想要的类型提示，`button` 组件 `type` 类型报错。

![image](https://github.com/uni-helper/uni-app-types/assets/36911513/67d5cfab-67fd-4796-9686-fcd67bbe41a9)

我看了之前的 `issues` 可以通过配置 `vueCompilerOptions.nativeTags` 来解决这个问题，但是是我查了一下，并没有找到这个配置的相关资料。

我对 `tsconfig` 这块的知识并不丰富，但是我想要知道这个配置是做什么的，有什么用，请问是否可以提供给我一点参考资料或文章之类的，感谢。

**Comment by ModyQyW** [comment]
你可以主要参考 [vuejs/language-tools](https://github.com/vuejs/language-tools) 的 [CHANGELOG](https://github.com/vuejs/language-tools/blob/master/CHANGELOG.md)。

在 0.34.16 版本，增加了 `vueCompilerOptions.experimentalRuntimeMode` 来适配 `uni-app`。

<img width="656" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/a6a51ae8-4bbb-4225-a6f2-0887366b7455">

在 1.0.10 版本，增加了 `vueCompilerOptions.nativeTags` 并移除了 `vueCompilerOptions.experimentalRuntimeMode`。

<img width="818" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/f1e51268-06ee-4127-9f20-c100ebf38781">

在 1.5.1 版本，废弃了 `vueCompilerOptions.nativeTags`。

<img width="545" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/349be164-aeda-4d5c-a0d4-0db7683f59a5">

在 1.7.12 版本，由于性能问题再次引入了 `vueCompilerOptions.nativeTags`。

<img width="630" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/4fd34da4-a591-47fd-9c3a-d6dc51d1ecd9">

vue-tsc 的作者 @ 过我，但我之前有点忙，还没有把文档更新推送上来。现在已经更新推送了，非常抱歉 🙏

**Comment by Ares-Chang** [comment]
Thanks
