### ISSUE TITLE
volar >1.7.12  如何配置?

### ISSUE THREAD

**Issue by zhuddan** [uni-helper/uni-app-types#50]
### 描述问题

valor 和 vue-tsc 当前为1.8.8版本（降低版本到1.6.5可正常，但不想这么做，可能会影响其他vue项目 ），uni-helper/uni-app-types 中的类型似乎不能正常工作。
可以 image 和  button 可以跳转到 @uni-helper/uni-app-types 文件中，但类型提示不正常。
之前 button type="primary" 会和原生 button type 的冲突，但现在不会。

![image](https://github.com/uni-helper/uni-app-types/assets/32126992/6ad3e0bb-cdfc-47e6-bd9a-49f1454818ad)
![image](https://github.com/uni-helper/uni-app-types/assets/32126992/4122cd95-c98f-4a85-91aa-65ce89985dbd)

### 复现

valor & vue-tsc 均为 1.8.8 vue 为 3.3.4，且尝试 tsconfig 配置 vueCompilerOptions 与否均未生效
附tsconfig
![image](https://github.com/uni-helper/uni-app-types/assets/32126992/898185c0-ac0b-4444-90ee-b7378a8c3596)

### 系统信息

```Shell
System:
    OS: Windows 10 10.0.22621
    CPU: (32) x64 13th Gen Intel(R) Core(TM) i9-13900HX
    Memory: 18.63 GB / 31.74 GB
  Binaries:
    Node: 16.20.1 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - D:\Program Files\nodejs\yarn.CMD
    npm: 8.19.4 - D:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.6 - D:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22621.1992.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
在我的本地环境（volar 1.8.8 + vue 3.3）一切正常

<img width="917" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/d2cb2c90-b8bf-40ff-96e9-6562e7bc2acc">

会不会漏了什么配置呢？

- 如果是使用 yarn v2/v3 或者 pnpm 安装依赖需要额外配置
- volar 需要启用接管模式，或者安装 TypeScript Vue Plugin
- 需要设置 tsconfig.json vueCompilerOptions.nativeTags
- 必要时重启 VS Code

如果仍然无效，可以麻烦提供一下 demo 吗？谢谢🙏

**Comment by zhuddan** [comment]
谢谢你的回复！十分抱歉！我的tsconfig配置存在问题，现在已经可以正常工作了。
