### ISSUE TITLE
volar >= 1.8.12 标签报错

### ISSUE THREAD

**Issue by yikoyu** [uni-helper/uni-app-types#52]
### 描述问题

volar 版本 >= 1.8.12, view image text标签全部报错
![Snipaste_2023-09-22_14-39-57](https://github.com/uni-helper/uni-app-types/assets/46991966/9d712b28-0581-4310-a72e-8168ca77d97d)

### 复现

vscode插件volar 版本 >= 1.8.12 报错，降级到 1.8.11 正常

tsconfig.json
```json
{
  "extends": "@vue/tsconfig/tsconfig.json",
  "compilerOptions": {
    "sourceMap": true,
    "baseUrl": ".",
    "noImplicitAny": false,
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "paths": {
      "@/*": ["./src/*"]
    },
    "lib": ["esnext", "dom"],
    "types": ["node", "@dcloudio/types", "@types/wechat-miniprogram", "@uni-helper/uni-app-types"]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue", "types/**/*.d.ts", "types/**/*.ts"]
}
```

### 系统信息
vue 3.2.45

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz    
    Memory: 4.66 GB / 15.86 GB
  Binaries:
    Node: 16.15.1 - ~\AppData\Local\pnpm\node.EXE
    Yarn: 1.22.19 - ~\AppData\Local\pnpm\yarn.CMD
    npm: 8.11.0 - ~\AppData\Local\pnpm\npm.CMD
    pnpm: 8.3.1 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (117.0.2045.36)
    Internet Explorer: 11.0.19041.1566
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
我这边在使用 volar 1.8.13，但没有出现你提到的问题。

<img width="1512" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/a1a1352e-326e-42d7-9afc-35eea10d10e1">

能否请你检查一下项目配置呢？

1. 需要启用 [接管模式 Takeover Mode](https://cn.vuejs.org/guide/typescript/overview.html#volar-takeover-mode)。如果不想启用接管模式，可以安装 [TypeScript Vue Plugin (Volar)](https://marketplace.visualstudio.com/items?itemName=Vue.vscode-typescript-vue-plugin)。启用或安装后需要重启 VSCode。
2. 不要忘了在相应的`tsconfig.json `里面配置 `vueCompilerOptions`，重启 VSCode
<img width="688" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/82791034-a934-431f-a36e-886e385fe41c">

**Comment by KeJunMao** [comment]
![image](https://github.com/uni-helper/uni-app-types/assets/18414281/7b34976f-b6fb-49db-a543-fe2463987eca)
无法复现 +1

**Comment by yikoyu** [comment]
感谢回复，问题已解决，原因是未在 `tsconfig.json` 中添加 `vueCompilerOptions` 配置，导致异常。

就是以前啥问题也没有，今天啥都没动，突然报错了

**Comment by ModyQyW** [comment]
> 今天啥都没动，突然报错了

This is life. 😄
