### ISSUE TITLE
webstorm 类型提示不出来

### ISSUE THREAD

**Issue by zws-code** [uni-helper/uni-app-types#56]
### 描述问题

webstorm  2023.2 版本后 已经内置volar了 [https://cn.vuejs.org/guide/typescript/overview.html#ide-support](https://cn.vuejs.org/guide/typescript/overview.html#ide-support)
按照教程已修改完配置 同一个项目 
vscode 有提示 
<img width="856" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/19341509/2ea7cb25-af53-47db-9318-c575e4f6ac4b">

webstorm提示不出来.
<img width="856" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/19341509/432661b8-0379-4fb3-91c1-2a4088ad4921">

不知道什么原因 

### 复现

webstorm 2023.2.4版本
<img width="742" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/19341509/bc00f8c4-b0cc-4141-a52e-10d9ff06614b">

### 系统信息

```Shell
System:
    OS: macOS 14.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 298.42 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.1.0 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 10.2.0 - /opt/homebrew/bin/npm
    pnpm: 8.9.2 - /opt/homebrew/bin/pnpm
    Watchman: 2023.10.23.00 - /opt/homebrew/bin/watchman
  Browsers:
    Chrome: 118.0.5993.117
    Safari: 17.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
<img width="344" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/9734c107-cf61-46bc-b948-109649c0242d">

<img width="361" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/5928df30-1e81-4c50-866b-0270bf9aec5c">

<img width="356" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/f5e3ce5f-a11d-4a02-8547-f2ca21e3de89">




在我的本地项目无法复现，请提供一个最小复现。

但是发现另外一个问题，属性类型无法正常推导，在 script 标签内定义的方法在 template 内也无法正常推导。既然这些东西在 VSCode 都是正常的，而且非 uni-app 项目在 WebStorm 里也是正常的，我感觉是 WebStorm 本身支持不足的问题。

<img width="355" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/14515ea9-8b7a-44f4-9f85-43f79c5bf902">

<img width="783" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/a40752a8-8602-4d70-a239-c282ddab5510">

<img width="452" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/aef936c2-7dc0-4ec3-96e8-969619d58688">

**Comment by zws-code** [comment]
@ModyQyW 
最小复现步骤 参考uniapp 官方拉一个vue3 ts 模板  然后再添加本库 types
1 npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project
2 pnpm add -D @uni-helper/uni-app-types
修改tsconfig.json 和 .npmrc 其他都没用动了  webstorm还是一样 无法提示.... vscode 依然可以 很邪门
另外 webstorm 的配置我不太清楚怎么提供

tsconfig.json
{
  "extends": "@vue/tsconfig/tsconfig.json",
  "compilerOptions": {
    "sourceMap": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    },
    "lib": ["esnext", "dom"],
    "types": [
      "@dcloudio/types",
      "@uni-helper/uni-app-types",
    ]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
  "vueCompilerOptions": {
    "experimentalRuntimeMode": "runtime-uni-app",
    "nativeTags": ["block", "component", "template", "slot"]
  }
}
.npmrc
shamefully-hoist=true

**Comment by ModyQyW** [comment]
<img width="535" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/224e9196-2c53-4eb9-8c43-8853da8f4dc4">

**Comment by zws-code** [comment]
@ModyQyW 
[settings.zip](https://github.com/uni-helper/uni-app-types/files/13195779/settings.zip)

**Comment by ModyQyW** [comment]
我的 WebStorm 也是 2023.2.4，导入你的设置后还是不会出现`未知 HTML 标记` 的提示，实在复现不出来，说不定你重启一下 IDE 重新索引一下就好了。

属性类型推导问题可以肯定是 WebStorm 的问题，需要 WebStorm 解决。

**Comment by zws-code** [comment]
找到原因了 我尝试了一下 用npm yarn 居然是正常的  
对比了一下 node_modules目录 发现pnpm 都是软连接
shamefully-hoist=true 配置 平铺了 node_modules 的结构 但还是软连接 
换另一个配置就正常了
node-linker=hoisted
[https://pnpm.io/zh/npmrc#node-linker](https://pnpm.io/zh/npmrc#node-linker)
[https://pnpm.io/zh/npmrc#shamefully-hoist](https://pnpm.io/zh/npmrc#shamefully-hoist)
<img width="1182" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/19341509/2bb2fc30-dacd-42e2-9d47-a7769e6bdeb8">
<img width="419" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/19341509/a22f4476-319a-4f32-9035-f85f02db5318">

**Comment by ModyQyW** [comment]
我这边 pnpm@8.9.2 没有配置 node_linker 也是正常的，只配置了 shamefully-hoist=true，神奇

**Comment by ModyQyW** [comment]
先关闭这个 issue 了，因为这边对该问题无能为力。🙏
