### ISSUE TITLE
"experimentalRuntimeMode": "runtime-uni-app" 不起作用

### ISSUE THREAD

**Issue by Secret1007** [uni-helper/uni-app-types#59]
### 描述问题

experimentalRuntimeMode 这个值已经弃用了吗

### 复现

![image](https://github.com/uni-helper/uni-app-types/assets/87068106/afce7bb8-1cbc-44b7-875f-a4c0eaf0e5db)

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 4.86 GB / 15.80 GB
  Binaries:
    Node: 16.17.0 - D:\nvm-symlink\node.EXE
    Yarn: 1.22.19 - D:\nvm-symlink\yarn.CMD
    npm: 8.15.0 - D:\nvm-symlink\npm.CMD
    pnpm: 8.3.1 - D:\nvm-symlink\pnpm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (118.0.2088.61)
    Internet Explorer: 11.0.22000.120
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
<img width="721" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/ce257270-cbeb-4220-84f7-d0bc2482346e">

README 里面已经写明白适用的 volar 版本号了。volar >= 1.0.10 已经弃用这个字段。

**Comment by Secret1007** [comment]
非常感谢。我正在学习阅读README,因为是英文加上项目不熟悉，所以README对我来说目前比较枯燥，今天学到了，问题也解决了😊

**Comment by Secret1007** [comment]
非常感谢。我正在学习阅读README,因为是英文加上项目不熟悉，所以README对我来说目前比较枯燥，今天学到了，问题也解决了😊
