### ISSUE TITLE
the new version of vue-official can't support nativeTags

### ISSUE THREAD

**Issue by ccc0818** [uni-helper/uni-app-types#61]
### 描述问题

<img width="937" alt="Snipaste" src="https://github.com/uni-helper/uni-app-types/assets/56196628/3ae73b1c-0761-4e29-809c-b40ecc2bd026">

### 复现

install vscode vue-official 2.0.16

# tsconfig
{
  "extends": "@vue/tsconfig/tsconfig.json",
  "compilerOptions": {
    "ignoreDeprecations": "5.0",
    "sourceMap": true,
    "baseUrl": ".",
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "moduleResolution": "node",
    "esModuleInterop": true,
    "skipLibCheck": true,
    "importHelpers": true,
    "allowSyntheticDefaultImports": true,
    "useDefineForClassFields": true,
    "resolveJsonModule": true,
    "paths": {
      "@/*": ["./src/*"]
    },
    "lib": ["esnext", "dom"],
    "types": [
      "@dcloudio/types",
      "@uni-helper/uni-app-types",
      "@types/wechat-miniprogram"
    ]
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
  //加入配置，将标签视为原始组件
  "vueCompilerOptions": {
    "nativeTags": ["block", "component", "template", "slot"]
  }
}

### 系统信息

macos 14 sonoma

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by xue-lei** [comment]
![image](https://github.com/uni-helper/uni-app-types/assets/59636936/33c59a9b-1e88-4b48-924d-c712dea78996)
upgrade to "@uni-helper/uni-app-types": "^0.5.13"
