### ISSUE TITLE
升级 Vue 到新版本后, 类型失效

### ISSUE THREAD

**Issue by Zhang-Wei-666** [uni-helper/uni-app-types#62]
### 描述问题

在最近的 uniapp 更新中 [4.14.2024043013](https://uniapp.dcloud.net.cn/release.html#_4-14-2024043013), 升级了 vue 版本 `3.2.47` -> `3.4.21`, 应该是新版本的 vue 内置了 `view`、`text` 等的类型, 估计是优先级比 `uni-app-types` 的高, 内置组件的类型提示不再生效了

![image](https://github.com/uni-helper/uni-app-types/assets/37876877/0beb01be-05a5-47ae-ace4-e9baccc33961)

![image](https://github.com/uni-helper/uni-app-types/assets/37876877/977fe30e-60fc-4356-b5aa-8396e05ad54d)

![image](https://github.com/uni-helper/uni-app-types/assets/37876877/630d5d44-252e-4112-bb6c-0b6b10b211ae)

---

其他的似乎没问题
![image](https://github.com/uni-helper/uni-app-types/assets/37876877/1139b927-e275-4a85-9994-38907f19b7d9)

### 复现

https://github.com/MoomFE-Starter-Template/UniApp-Base

### 系统信息

基础环境信息:
  - os: `Windows 11 10.0.22631`
  - node: `20.12.2`
  - vscode: `1.89.1`
  - volar: `2.0.16`

基础依赖信息:
  - vue: `3.4.21`
  - vite: `5.2.11`
  - @dcloudio/uni-app: `3.0.0-4010520240507001`

uni-helper依赖信息:
  - @uni-helper/uni-ui-types: `0.5.13`

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
<img width="700" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/31850793/9a49e09a-14cd-4f2f-a2bc-8761ea4a7997">
更新一下你的 tsconfig.json za再试试吧

**Comment by Zhang-Wei-666** [comment]
可以的, 现在类型有了, 但是组件本身的注释似乎还是没显示, 不过问题也不大了

![image](https://github.com/uni-helper/uni-app-types/assets/37876877/99252748-1dfe-4230-a292-da62c2c69396)

![image](https://github.com/uni-helper/uni-app-types/assets/37876877/a7bd47e4-fd0d-4843-b186-e73b329356d6)

**Comment by ModyQyW** [comment]
组件本身注释缺失我也无能为力，源代码里面已经设置了注释，但是 volar 没有显示出来，这个问题可以向 volar 提 issue 看看。

**Comment by ModyQyW** [comment]
@Zhang-Wei-666 Checkout https://github.com/vuejs/language-tools/issues/4378#issuecomment-2111439387
