### ISSUE TITLE
webstorm 上会对模版上的 class 显示异常

### ISSUE THREAD

**Issue by sunpm** [uni-helper/uni-app-types#63]
### 描述问题

<img width="1005" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/35005831/159493fa-aa74-4a98-a095-07af7c8c0036">
<img width="263" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/35005831/178027d5-65ca-4bd0-a29d-5fc7fe4d1212">

注释后，异常消失了
<img width="325" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/35005831/c6304b0a-d693-4c54-9580-b717414090db">
<img width="488" alt="image" src="https://github.com/uni-helper/uni-app-types/assets/35005831/f5b75ff4-f466-4be9-a1ca-477159089fad">

### 复现

https://github.com/sunpm/vitesse-uniapp-vue3
随便去一个 vue 文件 添加 <view class="demo">123</view> 都会显示异常😭

### 系统信息

Node: 18.17.1
pnpm: 9.1.1

WebStorm 2024.1.2

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
可以参考README添加vueCompilerOptions.plugins试试，uni-app-types需要用0.5.13版本![Screenshot_2024-05-14-19-28-19-97_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/uni-helper/uni-app-types/assets/31850793/53e086e9-83c7-42a9-b3e3-35a666eec260)

**Comment by sunpm** [comment]
> 可以参考README添加vueCompilerOptions.plugins试试，uni-app-types需要用0.5.13版本![Screenshot_2024-05-14-19-28-19-97_320a9a695de7cdce83ed5281148d6f19.jpg](https://private-user-images.githubusercontent.com/31850793/330406161-53e086e9-83c7-42a9-b3e3-35a666eec260.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3MzUyODMsIm5iZiI6MTcxNTczNDk4MywicGF0aCI6Ii8zMTg1MDc5My8zMzA0MDYxNjEtNTNlMDg2ZTktODNjNy00MmE5LWIzZTMtMzVhNjY2ZWVjMjYwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE1VDAxMDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3YmFhMDg2ODQyZGEyODdkYzY5YmQzMjgxNDAyNWI4YTgxMGNmNTBlZjg3NWJjMTAzYjY1YTBiNjU4NTQ3ZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IikSn-kge5JpJe5w9OuSVRlLWs2JAJuVjnNJ8pcyPXg)

确实，添加后不会报错了。好难啊，处是疑难杂症😭
