### ISSUE TITLE
volar@2.024(含)之后的版本失效

### ISSUE THREAD

**Issue by ci0n** [uni-helper/uni-app-types#66]
### 描述问题

volar@2.024于一周前发布，更新后类型提示失效

### 复现

volar插件更新到最新

### 系统信息

vscode输出面板中的错误信息：

[Vue] Plugin "@uni-helper/uni-app-types/volar-plugin (2)" API version incompatible, expected "2" but got "1".

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
https://github.com/vuejs/language-tools/issues/4501

如果你不是在用 ts 5.5，可以降级 volar 到 2.0.21

**Comment by ci0n** [comment]
> [vuejs/language-tools#4501](https://github.com/vuejs/language-tools/issues/4501)
> 
> 如果你不是在用 ts 5.5，可以降级 volar 到 2.0.21

我在用5.5..

**Comment by ModyQyW** [comment]
> > [vuejs/language-tools#4501](https://github.com/vuejs/language-tools/issues/4501)
> > 如果你不是在用 ts 5.5，可以降级 volar 到 2.0.21
> 
> 我在用5.5..

我发的链接里就有 5.5 的解决方案

**Comment by llhxhal** [comment]
> [vuejs/language-tools#4501](https://github.com/vuejs/language-tools/issues/4501)
> 
> 如果你不是在用 ts 5.5，可以降级 volar 到 2.0.21

好好好，原来是版本问题，我还以为是我的问题

**Comment by ModyQyW** [comment]
https://github.com/uni-helper/uni-app-types/issues/67

**Comment by ModyQyW** [comment]
我即将归档这个仓库并将工作迁移到 [@uni-helper/uni-types](https://github.com/uni-helper/uni-types) 中继续进行
